# MDP Example

Here we will implement the Policy Evaluation, Value Iteration and Value Iteration algorithms

Recall, the MDP we consider in module 1 is 

<img src="mdp-cs747.png" 
     align="center" 
     width="300" />
     
For the above MDP, the transition probaility matrix is given by


$$
\mathcal{P}(s'|s,a = RED) = 
\begin{bmatrix}
0.5 & 0.5 & 0 \\
0.25 & 0 & 0.75\\
0 & 0.5 & 0.5
\end{bmatrix}
,~~~and~~~
\mathcal{P}(s'|s,a = BLUE) = 
\begin{bmatrix}
1 & 0 & 0 \\
1 & 0 & 0 \\
1 & 0 & 0
\end{bmatrix}
$$

The reward function is 

$$
\mathcal{R}(s'|s,a = RED) = 
\begin{bmatrix}
0 & -1 & 0 \\
-1 & 0 & -2\\
0 & 3 & 3
\end{bmatrix}
,~~~and~~~
\mathcal{R}(s'|s,a = BLUE) = 
\begin{bmatrix}
1 & 0 & 0 \\
2 & 0 & 0 \\
1 & 0 & 0
\end{bmatrix}
$$

We first implement the Policy Evaluation for various policies

# Policy Evaluation

In [33]:
import numpy as np

# Define MDP parameters
num_states = 3  # [0,1,2]
num_actions = 2 # [0,1]
gamma = 0.9  # discount factor

# Define rewards and transition probabilities
R = np.zeros((num_states, num_actions, num_states))
R[0, 0, :] = [0,1,0]
R[0, 1, :] = [1,0,0]
R[1, 0, :] = [-1,0,-2]
R[1, 1, :] = [2,0,0]
R[2, 0, :] = [0,3,3]
R[2, 1, :] = [1,0,0]

# Define the transition probabilities for each state and action
P = np.zeros((num_states, num_actions, num_states))
P[0, 0, :] = [0.5, 0.5, 0]
P[0, 1, :] = [1, 0, 0]
P[1, 0, :] = [0.25, 0, 0.75]
P[1, 1, :] = [1, 0, 0]
P[2, 0, :] = [0, 0.5, 0.5]
P[2, 1, :] = [1, 0, 0]


# Initialize value function
V = np.zeros(num_states)

# Perform policy evaluation
tolerance = 1e-6
delta = np.inf

def policy_evaluation(transitions, rewards, policy, gamma, theta=0.0001):
    num_states, num_actions, _ = transitions.shape
    V = np.zeros(num_states)
    while True:
        delta = 0
        for s in range(num_states):
            value = 0
            for action in range(num_actions):
                action_prob = policy[s][action]
                for next_state in range(num_states):
                    prob = transitions[s][action][next_state]
                    value += action_prob * prob * (rewards[s][action][next_state] + gamma * V[next_state])
            delta = max(delta, abs(value - V[s]))
            V[s] = value
        if delta < theta:
            break
    return V

# Define policy
policy = np.array([[0, 1], [0, 1], [0, 1]])  # deterministic policy
## If the policy is RRB then the polcy will be written as [[1,0],[1,0], [0,1]]
## If the policy is BRB then the polcy will be written as [[0,1],[1,0], [1,0]] etc.

val = policy_evaluation(P, R, policy, gamma, theta=0.0001)
print(val)

[ 9.99915359 10.99923823  9.99923823]


# Value Iteration

In [29]:
import numpy as np

# Define the MDP parameters
num_states = 3
num_actions = 2

# Define the transition probabilities for each state and action
P = np.zeros((num_states, num_actions, num_states))
P[0, 0, :] = [0.5, 0.5, 0]
P[0, 1, :] = [1, 0, 0]
P[1, 0, :] = [0.25, 0, 0.75]
P[1, 1, :] = [1, 0, 0]
P[2, 0, :] = [0, 0.5, 0.5]
P[2, 1, :] = [1, 0, 0]

# Define the reward function for each state and action
R = np.zeros((num_states, num_actions, num_states))
R[0, 0, :] = [0,1,0]
R[0, 1, :] = [1,0,0]
R[1, 0, :] = [-1,0,-2]
R[1, 1, :] = [2,0,0]
R[2, 0, :] = [0,3,3]
R[2, 1, :] = [1,0,0]

# Define the discount factor and convergence threshold
gamma = 0.9
epsilon = 0.001



# Initialize the value function to zeros
V = np.zeros(num_states)

# Run the value iteration algorithm
while True:
    delta = 0
    for s in range(num_states):
        v_old = V[s]
        # Calculate the new value for each state
        V[s] = max([sum([P[s, a, s1] * (R[s, a, s1] + gamma * V[s1]) for s1 in range(num_states)]) for a in range(num_actions)])
        # Check for convergence
        delta = max(delta, abs(V[s] - v_old))
    if delta < epsilon:
        break

# Print the final value function
print("Final value function:")
print(V)


Final value function:
[ 9.99174648 10.99257183 14.4478601 ]


# Policy Iteration

In [8]:
import numpy as np

# Define the MDP parameters
num_states = 3
num_actions = 2

# Define the transition probabilities for each state and action
P = np.zeros((num_states, num_actions, num_states))
P[0, 0, :] = [0.5, 0.5, 0]
P[0, 1, :] = [1, 0, 0]
P[1, 0, :] = [0.25, 0, 0.75]
P[1, 1, :] = [1, 0, 0]
P[2, 0, :] = [0, 0.5, 0.5]
P[2, 1, :] = [1, 0, 0]

# Define the reward function for each state and action
R = np.zeros((num_states, num_actions, num_states))
R[0, 0, :] = [0,1,0]
R[0, 1, :] = [1,0,0]
R[1, 0, :] = [-1,0,-2]
R[1, 1, :] = [2,0,0]
R[2, 0, :] = [0,3,3]
R[2, 1, :] = [1,0,0]

# Define the discount factor and convergence threshold
gamma = 0.9

# Define the policy
policy = np.array([[1, 0], [1, 0], [1, 0]])

V = np.zeros(num_states)
tolerance = 1e-6
delta = np.inf

# policy = np.zeros((num_states, num_actions))
# policy[:, 0] = 1

## policy Evaluation

def policy_evaluation(transitions, rewards, policy, gamma, theta=0.0001):
    num_states, num_actions, _ = transitions.shape
    while True:
        delta = 0
        for s in range(num_states):
            value = 0
            for action in range(num_actions):
                action_prob = policy[s][action]
                for next_state in range(num_states):
                    prob = transitions[s][action][next_state]
                    value += action_prob * prob * (rewards[s][action][next_state] + gamma * V[next_state])
            delta = max(delta, abs(value - V[s]))
            V[s] = value
        if delta < theta:
            break
    return V



# Run policy iteration
num_iterations = 20
for i in range(num_iterations):
    # Policy evaluation
    val = policy_evaluation(P, R, policy, gamma, theta=0.0001)
    # Policy improvement
    policy_stable = True
    for s in range(num_states):
        old_action = np.argmax(policy[s])
        action_values = np.zeros(num_actions)
        for a in range(num_actions):
            action_values[a] = np.sum(R[s, a, :]*P[s, a, :] + gamma * val * P[s, a, :])
        best_action = np.argmax(action_values)
        if old_action != best_action:
            policy_stable = False
            policy[s, :] = 0
            policy[s, best_action] = 1
    if policy_stable:
        break

print("Optimal policy:")
print(policy)
print("Optimal value function:")
print(V)


Optimal policy:
[[0 1]
 [0 1]
 [1 0]]
Optimal value function:
[ 9.99918039 10.99926235 14.45388157]
